import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import './globals.css'

const poppinsSans = Poppins({
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  style: 'normal',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="es">
      <body
        className={`${poppinsSans.className} antialiased w-screen h-screen`}
      >
        {children}
      </body>
    </html>
  )
}
