export const ROLES = {
  ADMIN: 'ADMIN',
  MANAGER_ADMIN: 'MANAGER_ADMIN',
  MANAGER_LOGISTICS: 'MANAGER_LOGISTICS',
  MANAGER_OPERATIONS: 'MANAGER_OPERATIONS',
  ASIST: 'ASIST',
  TECHNICIAN: 'TECHNICIAN',
} as const;

export const SYSTEM_ROLES = { SUPER_ADMIN: 'SUPER_ADMIN', ADMIN: 'ADMIN' } as const;
