export const TYPES = {
  RoleRepository: Symbol.for('RoleRepository'),
  RolesPrismaRepository: Symbol.for('RolesPrismaRepository'),
  RoleService: Symbol.for('RoleService'),
  CreateRoleUseCase: Symbol.for('CreateRoleUseCase'),
  CreateService: Symbol.for('CreateService'),
  RolesController: Symbol.for('RolesController'),
  RolesRoutes: Symbol.for('RolesRoutes'),
  ListRoleUseCase: Symbol.for('ListRoleUseCase'),
  ListService: Symbol.for('ListService'),
  GetRoleUseCase: Symbol.for('GetRoleUseCase'),
  GetRoleService: Symbol.for('GetRoleService'),
  UpdateRoleUseCase: Symbol.for('UpdateRoleUseCase'),
  UpdateRoleService: Symbol.for('UpdateRoleService'),
  DeleteRoleUseCase: Symbol.for('DeleteRoleUseCase'),
  DeleteRoleService: Symbol.for('DeleteRoleService'),
  AddPermissionsToRoleUseCase: Symbol.for('AddPermissionsToRoleUseCase'),
  RemovePermissionsFromRoleUseCase: Symbol.for('RemovePermissionsFromRoleUseCase'),
  PermissionAssignmentService: Symbol.for('PermissionAssignmentService'),
};
