export const TYPES = {
  CustomerRepository: Symbol.for('CustomerRepository'),
  CreateCustomerService: Symbol.for('CreateCustomerService'),
  UpdateCustomerService: Symbol.for('UpdateCustomerService'),
  GetCustomerService: Symbol.for('GetCustomerService'),
  ListCustomersService: Symbol.for('ListCustomersService'),
  DeleteCustomerService: Symbol.for('DeleteCustomerService'),
  CreateCustomerUseCase: Symbol.for('CreateCustomerUseCase'),
  UpdateCustomerUseCase: Symbol.for('UpdateCustomerUseCase'),
  GetCustomerUseCase: Symbol.for('GetCustomerUseCase'),
  ListCustomersUseCase: Symbol.for('ListCustomersUseCase'),
  DeleteCustomerUseCase: Symbol.for('DeleteCustomerUseCase'),
  CustomerController: Symbol.for('CustomerController'),
  CustomerRoutes: Symbol.for('CustomerRoutes'),

  // SubCustomer
  SubCustomerRepository: Symbol.for('SubCustomerRepository'),
  CreateSubCustomerService: Symbol.for('CreateSubCustomerService'),
  UpdateSubCustomerService: Symbol.for('UpdateSubCustomerService'),
  GetSubCustomerService: Symbol.for('GetSubCustomerService'),
  ListSubCustomersService: Symbol.for('ListSubCustomersService'),
  DeleteSubCustomerService: Symbol.for('DeleteSubCustomerService'),
  CreateSubCustomerUseCase: Symbol.for('CreateSubCustomerUseCase'),
  UpdateSubCustomerUseCase: Symbol.for('UpdateSubCustomerUseCase'),
  GetSubCustomerUseCase: Symbol.for('GetSubCustomerUseCase'),
  ListSubCustomersUseCase: Symbol.for('ListSubCustomersUseCase'),
  DeleteSubCustomerUseCase: Symbol.for('DeleteSubCustomerUseCase'),
  SubCustomerController: Symbol.for('SubCustomerController'),
  SubCustomerRoutes: Symbol.for('SubCustomerRoutes'),
};
