export const TYPES = {
  ShowUserService: Symbol.for('ShowUserService'),
  ShowMeUseCaseService: Symbol.for('ShowMeUseCaseService'),
  UserRepository: Symbol.for('UsersRepository'),
  UsersService: Symbol.for('UsersService'),
  UsersController: Symbol.for('UsersController'),
  UsersRoutes: Symbol.for('UsersRoutes'),
  UpdateMeUseCaseService: Symbol.for('UpdateMeUseCaseService'),
  ListUsersService: Symbol.for('ListUsersService'),
  ShowAllUseCaseService: Symbol.for('ShowAllUseCaseService'),
  CreateUserUseCaseService: Symbol.for('CreateUserUseCaseService'),
  UpdateUserUseCaseService: Symbol.for('UpdateUserUseCaseService'),
  ShowUserUseCaseService: Symbol.for('ShowUserUseCaseService'),
  CreateUserService: Symbol.for('CreateUserService'),
  UpdateUserService: Symbol.for('UpdateUserService'),
};
